name             'base'
maintainer       'Pablo Gutiérrez del Castillo'
maintainer_email 'pablogutierrezdelc@gmail.com'
license          'All rights reserved'
description      'Installs/Configures base'
long_description 'Installs/Configures base'
version          '0.1.0'

supports         'debian'
supports         'ubuntu'

depends          'apt'
depends          'build-essential'
depends          'monit-ng'
depends          'openssh'
depends          'sudo'
depends          'timezone-ii'
